import { NextResponse } from "next/server";
import { requireTenantViaticos, requireTenantViaticosAutorizar, requireTenantViaticosPagar, requireTenantViaticosLiquidar } from "@/lib/tenant";
import { catalogosRequerimientoViatico, ErrorRequerimientoViatico, guardarRequerimientoViatico, listarRequerimientosViatico, obtenerRequerimientoViatico, transicionarRequerimientoViatico } from "./viaticos-requerimientos";
import { guardarRequerimientoViaticoSchema, transicionRequerimientoViaticoSchema } from "./viaticos-requerimientos-schema";

const json=(v:unknown,status=200)=>NextResponse.json(v,{status,headers:{"Cache-Control":"private, no-store"}});
const validId=(v:string)=>/^[1-9]\d*$/.test(v)&&Number(v)<=2147483647;
const error=(e:unknown)=>e instanceof ErrorRequerimientoViatico?json({error:e.message},e.status):json({error:"No se pudo procesar el requerimiento de viáticos."},500);

export async function reqViaticosGet(slug:string,id?:string){const g=await requireTenantViaticos(slug,"ver");if(g.error)return g.error;if(id&&!validId(id))return json({error:"No encontrado."},404);try{if(id){const r=await obtenerRequerimientoViatico(g.empresa.id,Number(id));return json({requerimiento:r,esRequirente:!!r&&Number((r as Record<string,unknown>).requirente_usuario_id)===g.session.id});}return json({requerimientos:await listarRequerimientosViatico(g.empresa.id)});}catch(e){return error(e);}}
export async function reqViaticosCatalogos(slug:string){const g=await requireTenantViaticos(slug,"crear");if(g.error)return g.error;try{return json(await catalogosRequerimientoViatico(g.empresa.id));}catch(e){return error(e);}}
export async function reqViaticosGuardar(req:Request,slug:string,id?:string){const g=await requireTenantViaticos(slug,id?"editar":"crear");if(g.error)return g.error;if(id&&!validId(id))return json({error:"No encontrado."},404);let body:unknown;try{body=await req.json();}catch{return json({error:"JSON no válido."},400);}const p=guardarRequerimientoViaticoSchema.safeParse(body);if(!p.success)return json({error:p.error.issues[0]?.message||"Datos inválidos.",issues:p.error.flatten()},400);try{return json({requerimiento:await guardarRequerimientoViatico(g.empresa.id,g.session.id,g.session.username,p.data,id?Number(id):undefined)},id?200:201);}catch(e){return error(e);}}
export async function reqViaticosTransicion(req:Request,slug:string,id:string){if(!validId(id))return json({error:"No encontrado."},404);let body:unknown;try{body=await req.json();}catch{return json({error:"JSON no válido."},400);}const p=transicionRequerimientoViaticoSchema.safeParse(body);if(!p.success)return json({error:p.error.issues[0]?.message||"Datos inválidos."},400);const guard= p.data.accion==="autorizar"||p.data.accion==="rechazar"?await requireTenantViaticosAutorizar(slug,"editar"):p.data.accion==="entregar"?await requireTenantViaticosPagar(slug,"editar"):p.data.accion==="liquidar"?await requireTenantViaticosLiquidar(slug,"editar"):await requireTenantViaticos(slug,"editar");if(guard.error)return guard.error;try{return json({requerimiento:await transicionarRequerimientoViatico(guard.empresa.id,Number(id),guard.session.id,guard.session.username,guard.session.rol,p.data)});}catch(e){return error(e);}}
