import { describe, expect, it } from "vitest";
import { guardarRequerimientoViaticoSchema, nombreEmpresaRequirente, transicionRequerimientoViaticoSchema } from "./viaticos-requerimientos-schema";
const linea={fechaSolicitud:"2026-09-21",fechaViaje:"2026-09-23",personalId:3,vehiculoId:4,clienteId:5,cantidad:"2",destino:"Escuintla",montoUnitario:"100.25",motivoCambio:"Ruta especial",observaciones:null};
describe("requerimientos manuales de viáticos",()=>{
  const base={fechaRequerimiento:"2026-09-21",empresaRequirente:"KUIQTRANS" as const,requirenteUsuarioId:8,lineas:[linea]};
  it("acepta captura manual estricta y rechaza estado/snapshots/plan falsificados",()=>{expect(guardarRequerimientoViaticoSchema.safeParse(base).success).toBe(true);expect(guardarRequerimientoViaticoSchema.safeParse({...base,estado:"PENDIENTE"}).success).toBe(false);expect(guardarRequerimientoViaticoSchema.safeParse({...base,empresaRequirenteNombre:"falso"}).success).toBe(false);expect(guardarRequerimientoViaticoSchema.safeParse({...base,lineas:[{...linea,planId:9}]}).success).toBe(false);});
  it("valida catálogo cerrado y resuelve snapshots de las dos empresas",()=>{expect(nombreEmpresaRequirente("KUIQTRANS")).toBe("KuiqTrans");expect(nombreEmpresaRequirente("MONACO")).toBe("Logiservicios Mónaco");expect(guardarRequerimientoViaticoSchema.safeParse({...base,empresaRequirente:"Kuiqtrans / Logiservicios Mónaco"}).success).toBe(false);});
  it("fecha de solicitud y fecha de viaje son independientes y obligatorias",()=>{expect(guardarRequerimientoViaticoSchema.parse(base).lineas[0]).toMatchObject({fechaSolicitud:"2026-09-21",fechaViaje:"2026-09-23"});expect(guardarRequerimientoViaticoSchema.safeParse({...base,lineas:[{...linea,fechaViaje:undefined}]}).success).toBe(false);});
  it("cantidad debe ser positiva y montos tienen dos decimales",()=>{expect(guardarRequerimientoViaticoSchema.safeParse({...base,lineas:[{...linea,cantidad:"0"}]}).success).toBe(false);expect(guardarRequerimientoViaticoSchema.safeParse({...base,lineas:[{...linea,montoUnitario:"1.234"}]}).success).toBe(false);});
  it.each(["enviar","autorizar","rechazar","entregar","liquidar"])("valida payload de transición %s",accion=>{const body:Record<string,unknown>={accion,version:1};if(accion==="rechazar")body.motivo="Dato incorrecto";if(accion==="entregar")Object.assign(body,{metodo:"EFECTIVO",referencia:null,observaciones:null});if(accion==="liquidar")body.observaciones=null;expect(transicionRequerimientoViaticoSchema.safeParse(body).success).toBe(true);});
});
