import PDFDocument from "pdfkit";
import ExcelJS from "exceljs";
import { readFile, realpath } from "node:fs/promises";
import { resolve, sep } from "node:path";
import type { RowDataPacket } from "mysql2";
import { query } from "@/lib/db";
import { getUploadsRoot, validarRutaArchivoEmpresa } from "@/lib/uploads";
import { esPngValido, MAX_FIRMA_IMAGEN_BYTES } from "@/lib/firmas/imagen-firma";
import type { RequerimientoViatico } from "./viaticos-requerimientos-schema";

const txt=(v:unknown)=>String(v??"—").normalize("NFC");
const money=(v:unknown)=>`Q ${Number(v||0).toLocaleString("es-GT",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export async function firmaHistoricaRequerimientoViatico(empresaId:number,id:number):Promise<Buffer|null>{const rows=await query<RowDataPacket[]>(`SELECT imagen_ruta FROM firmas_electronicas WHERE empresa_id=? AND modulo='TMS' AND entidad_tipo='REQUERIMIENTO_VIATICO' AND entidad_id=? AND accion='AUTORIZAR_REQUERIMIENTO_VIATICO' ORDER BY id DESC LIMIT 1`,[empresaId,id]);try{const abs=validarRutaArchivoEmpresa(empresaId,rows[0]?.imagen_ruta);if(!abs)return null;const [root,file]=await Promise.all([realpath(resolve(getUploadsRoot(),"empresas",String(empresaId))),realpath(abs)]);if(!file.startsWith(root+sep))return null;const b=await readFile(file);return b.length<=MAX_FIRMA_IMAGEN_BYTES&&esPngValido(b)?b:null;}catch{return null;}}
export function requerimientoViaticoPdf(d:RequerimientoViatico,firmaAutorizante:Buffer|null=null):Promise<Buffer>{return new Promise((resolve,reject)=>{
  const doc=new PDFDocument({size:"LETTER",layout:"landscape",margins:{top:30,bottom:35,left:32,right:32},bufferPages:true});const chunks:Buffer[]=[];doc.on("data",c=>chunks.push(c as Buffer));doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject);
  const width=doc.page.width-64;doc.font("Helvetica-Bold").fontSize(15).text(txt(d.empresa_requirente_nombre),{align:"center",width});doc.fontSize(13).text("REQUERIMIENTO DE VIÁTICOS",{align:"center",width});doc.moveDown(.5);
  doc.font("Helvetica").fontSize(9).text(`Código: ${txt(d.codigo)}   Fecha: ${txt(d.fecha_requerimiento)}   Estado: ${txt(d.estado)}`);doc.text(`Persona que requiere: ${txt(d.requirente_nombre_snapshot)}   Solicitante: ${txt(d.solicitante_nombre_snapshot)}`);doc.moveDown(.5);
  const headers=["No.","Fecha solicitud","Fecha viaje","Colaborador","Cargo","Unidad","Cliente","Cantidad","Destino","Monto","Total"];const widths=[24,54,54,92,55,55,70,38,105,55,62];let y=doc.y;
  const header=()=>{let x=32;doc.font("Helvetica-Bold").fontSize(7);for(let i=0;i<headers.length;i++){doc.rect(x,y,widths[i],22).fillAndStroke("#1f4e78","#64748b");doc.fillColor("white").text(headers[i],x+3,y+7,{width:widths[i]-6,align:i>6?"right":"left"});x+=widths[i];}y+=22;};header();
  (d.lineas||[]).forEach((l,i)=>{if(y>doc.page.height-150){doc.addPage();y=32;header();}let x=32;const vals=[i+1,l.fecha_solicitud,l.fecha_viaje,l.personal_nombre_snapshot,l.cargo_snapshot,l.placa_snapshot,l.cliente_nombre_snapshot,l.cantidad,l.destino,money(l.monto_unitario),money(l.total)];doc.font("Helvetica").fontSize(7).fillColor("#0f172a");for(let j=0;j<vals.length;j++){doc.rect(x,y,widths[j],26).stroke("#94a3b8");doc.text(txt(vals[j]),x+3,y+5,{width:widths[j]-6,height:18,ellipsis:true,align:j===7||j>8?"right":"left"});x+=widths[j];}y+=26;});
  doc.y=y+8;doc.font("Helvetica-Bold").fontSize(11).text(`TOTAL: ${money(d.total)}`,32,doc.y,{width,align:"right"});if(d.observaciones)doc.font("Helvetica").fontSize(9).text(`Observaciones: ${txt(d.observaciones)}`);if(doc.y>doc.page.height-135)doc.addPage();const fy=doc.page.height-108;const fw=230;[["FIRMA DE LA PERSONA QUE REQUIERE",d.requirente_nombre_snapshot],["AUTORIZADO POR",d.autorizado_por_nombre]].forEach((a,i)=>{const x=90+i*400;if(i===1&&firmaAutorizante)doc.image(firmaAutorizante,x+45,fy-42,{fit:[140,38]});doc.moveTo(x,fy).lineTo(x+fw,fy).stroke();doc.font("Helvetica-Bold").fontSize(8).text(a[0] as string,x,fy+6,{width:fw,align:"center"});doc.font("Helvetica").text(txt(a[1]),x,fy+18,{width:fw,align:"center"});});
  const range=doc.bufferedPageRange();for(let i=0;i<range.count;i++){doc.switchToPage(range.start+i);doc.font("Helvetica").fontSize(7).fillColor("#64748b").text(`Página ${i+1} de ${range.count} · ${txt(d.codigo)}`,32,doc.page.height-24,{width,align:"center",lineBreak:false});}doc.end();});}

export async function requerimientoViaticoExcel(d:RequerimientoViatico):Promise<Buffer>{const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet("Requerimiento de viáticos");ws.columns=[6,14,14,24,18,14,22,10,32,14,14].map(width=>({width}));
  const title=(s:string,size:number)=>{const r=ws.addRow([s]);ws.mergeCells(r.number,1,r.number,11);r.font={bold:true,size};r.alignment={horizontal:"center"};};title(txt(d.empresa_requirente_nombre),16);title("REQUERIMIENTO DE VIÁTICOS",13);title(`${txt(d.codigo)} · ${txt(d.fecha_requerimiento)} · ${txt(d.estado)}`,10);ws.addRow([]);
  const h=ws.addRow(["No.","Fecha solicitud","Fecha viaje","Colaborador","Cargo","Unidad","Cliente","Cantidad","Destino","Monto","Total"]);h.font={bold:true,color:{argb:"FFFFFFFF"}};h.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF1F4E78"}};h.alignment={horizontal:"center",wrapText:true};
  (d.lineas||[]).forEach((l,i)=>ws.addRow([i+1,l.fecha_solicitud,l.fecha_viaje,l.personal_nombre_snapshot,l.cargo_snapshot,l.placa_snapshot,l.cliente_nombre_snapshot,Number(l.cantidad),l.destino,Number(l.monto_unitario),Number(l.total)]));ws.getColumn(10).numFmt='"Q "#,##0.00';ws.getColumn(11).numFmt='"Q "#,##0.00';const total=ws.addRow([null,null,null,null,null,null,null,null,null,"TOTAL",Number(d.total)]);total.font={bold:true};total.getCell(11).numFmt='"Q "#,##0.00';ws.autoFilter={from:{row:h.number,column:1},to:{row:h.number,column:11}};ws.views=[{state:"frozen",ySplit:h.number}];const out=await wb.xlsx.writeBuffer();return Buffer.from(out);}
