/** Categorías operativas Monaco + genéricas (seguro para cliente). */
export const CATEGORIAS_OPS = [
  "Piloto",
  "Auxiliar",
  "Auxiliar de Transporte",
  "Mensajero",
  "Mecánico",
  "Soldador",
  "Enderezador y Pintor",
  "Coordinador de logística",
  "Auxiliar de logística",
  "Gerente de operaciones",
  "Asistente de Recursos Humanos",
  "IT",
  "Gerente General",
  "Coordinador de predios",
  "Coordinador de compras",
  "Bodega",
  "Administrativo",
  "Otro",
] as const;
