"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { ParametroAjustes, PerfilAjustes } from "@/lib/tms/cotizacion-costeo-ajustes";

type Datos={hoy:string;parametros:ParametroAjustes[];perfiles:PerfilAjustes[]};
const cls="rounded border border-[var(--border)] bg-[var(--input)] px-2 py-1.5 text-sm";
const money=(v:number|null)=>v==null?"—":v.toLocaleString("es-GT",{style:"currency",currency:"GTQ"});
export const decimalAPorcentaje=(v:number|null)=>v==null?"":String(v*100);
export const porcentajeADecimal=(v:string)=>v.trim()===""?null:Number(v)/100;
/** Plantilla de una NUEVA vigencia: la última configuración disponible (el servidor ordena por vigente_desde DESC, id DESC), incluida una futura ya programada. NO es la "Vigencia actual" del badge (esa la marca el servidor en cada fila con esVigenciaActual). */
export const ultimaVigencia=(parametros:ParametroAjustes[]|undefined)=>parametros?.[0];
export function formularioNuevaVigencia(p:ParametroAjustes|undefined,hoy:string):Record<string,string>{return {vigenteDesde:hoy,precioCombustibleGalon:String(p?.precioCombustibleGalon??""),ivaTasa:decimalAPorcentaje(p?.ivaTasa??null),costoPilotoDia:String(p?.costoPilotoDia??0),costoAuxiliarDia:String(p?.costoAuxiliarDia??0),viaticoPilotoDia:String(p?.viaticoPilotoDia??0),viaticoAuxiliarDia:String(p?.viaticoAuxiliarDia??0),viaticoGuiaDia:String(p?.viaticoGuiaDia??0),hotelDia:p?.hotelDia?.toString()??"",margenObjetivo:decimalAPorcentaje(p?.margenObjetivo??null)};}
const vacioPerfil={codigo:"",nombre:"",activo:true,costoAdquisicion:"",diasOperacionMes:"",gpsMensual:"0",seguroVehiculoMensual:"0",costoAceiteServicio:"0",vidaUtilAceiteKm:"",costoJuegoLlantas:"0",vidaUtilLlantasKm:"",rendimientoKmGalon:"",deprecValorBase:"",deprecAnios:"",deprecDiasOperacionMes:"",refrigValorBase:"",refrigAnios:"",refrigDiasOperacionMes:""};
type PerfilForm=typeof vacioPerfil;
const numero=(v:string)=>Number(v);const nullable=(v:string)=>v.trim()===""?null:Number(v);
function payloadPerfil(f:PerfilForm){return {nombre:f.nombre.trim(),activo:f.activo,costoAdquisicion:nullable(f.costoAdquisicion),diasOperacionMes:numero(f.diasOperacionMes),gpsMensual:numero(f.gpsMensual),seguroVehiculoMensual:numero(f.seguroVehiculoMensual),costoAceiteServicio:numero(f.costoAceiteServicio),vidaUtilAceiteKm:numero(f.vidaUtilAceiteKm),costoJuegoLlantas:numero(f.costoJuegoLlantas),vidaUtilLlantasKm:numero(f.vidaUtilLlantasKm),rendimientoKmGalon:numero(f.rendimientoKmGalon),deprecValorBase:nullable(f.deprecValorBase),deprecAnios:nullable(f.deprecAnios),deprecDiasOperacionMes:nullable(f.deprecDiasOperacionMes),refrigValorBase:nullable(f.refrigValorBase),refrigAnios:nullable(f.refrigAnios),refrigDiasOperacionMes:nullable(f.refrigDiasOperacionMes)};}
function formPerfil(p:PerfilAjustes):PerfilForm{return {codigo:p.codigo,nombre:p.nombre,activo:p.activo,costoAdquisicion:p.costoAdquisicion?.toString()??"",diasOperacionMes:String(p.diasOperacionMes),gpsMensual:String(p.gpsMensual),seguroVehiculoMensual:String(p.seguroVehiculoMensual),costoAceiteServicio:String(p.costoAceiteServicio),vidaUtilAceiteKm:String(p.vidaUtilAceiteKm),costoJuegoLlantas:String(p.costoJuegoLlantas),vidaUtilLlantasKm:String(p.vidaUtilLlantasKm),rendimientoKmGalon:String(p.rendimientoKmGalon),deprecValorBase:p.deprecValorBase?.toString()??"",deprecAnios:p.deprecAnios?.toString()??"",deprecDiasOperacionMes:p.deprecDiasOperacionMes?.toString()??"",refrigValorBase:p.refrigValorBase?.toString()??"",refrigAnios:p.refrigAnios?.toString()??"",refrigDiasOperacionMes:p.refrigDiasOperacionMes?.toString()??""};}

export function CotizacionAjustesClient({slug,puedeCrear,puedeEditar}:{slug:string;puedeCrear:boolean;puedeEditar:boolean}){
 const [datos,setDatos]=useState<Datos|null>(null),[error,setError]=useState(""),[msg,setMsg]=useState(""),[tab,setTab]=useState<"parametros"|"perfiles">("parametros");
 const [mostrarParametro,setMostrarParametro]=useState(false),[perfilId,setPerfilId]=useState<number|null>(null),[pf,setPf]=useState<PerfilForm>(vacioPerfil);
 const cargar=useCallback(async()=>{setError("");const r=await fetch(`/api/empresas/${slug}/tms/cotizaciones/ajustes`,{cache:"no-store"});const j=await r.json();if(!r.ok){setError(j.error||"No se pudo cargar.");return;}setDatos(j);},[slug]);
 useEffect(()=>{
   let vigente=true;
   void fetch(`/api/empresas/${slug}/tms/cotizaciones/ajustes`,{cache:"no-store"}).then(async r=>({r,j:await r.json()})).then(({r,j})=>{
     if(!vigente)return;
     if(!r.ok){setError(j.error||"No se pudo cargar.");return;}
     setDatos(j);
   }).catch(()=>{if(vigente)setError("No se pudo cargar.");});
   return()=>{vigente=false;};
 },[slug]);
 const plantillaVigencia=useMemo(()=>ultimaVigencia(datos?.parametros), [datos]);
 const [pa,setPa]=useState<Record<string,string>>({});
 function nuevaVigencia(){setPa(formularioNuevaVigencia(plantillaVigencia,datos?.hoy??""));setMostrarParametro(true);}
 async function guardarParametro(e:React.FormEvent){e.preventDefault();setError("");const body={vigenteDesde:pa.vigenteDesde,precioCombustibleGalon:numero(pa.precioCombustibleGalon),ivaTasa:porcentajeADecimal(pa.ivaTasa),costoPilotoDia:numero(pa.costoPilotoDia),costoAuxiliarDia:numero(pa.costoAuxiliarDia),viaticoPilotoDia:numero(pa.viaticoPilotoDia),viaticoAuxiliarDia:numero(pa.viaticoAuxiliarDia),viaticoGuiaDia:numero(pa.viaticoGuiaDia),hotelDia:nullable(pa.hotelDia),margenObjetivo:porcentajeADecimal(pa.margenObjetivo)};const r=await fetch(`/api/empresas/${slug}/tms/cotizaciones/ajustes/parametros`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setError(j.error||"No se pudo guardar.");return;}setMsg("Nueva vigencia creada.");setMostrarParametro(false);await cargar();}
 function editarPerfil(p?:PerfilAjustes){setPerfilId(p?.id??null);setPf(p?formPerfil(p):{...vacioPerfil});}
 async function guardarPerfil(e:React.FormEvent){e.preventDefault();setError("");const url=perfilId?`/api/empresas/${slug}/tms/cotizaciones/ajustes/perfiles/${perfilId}`:`/api/empresas/${slug}/tms/cotizaciones/ajustes/perfiles`;const body=perfilId?payloadPerfil(pf):{codigo:pf.codigo.trim().toUpperCase(),...payloadPerfil(pf)};const r=await fetch(url,{method:perfilId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setError(j.error||"No se pudo guardar.");return;}setMsg(perfilId?"Perfil actualizado.":"Perfil creado.");setPerfilId(null);setPf(vacioPerfil);await cargar();}
 if(!datos&&!error)return <p className="p-6">Cargando ajustes…</p>;
 return <main className="space-y-4 p-6"><div><h1 className="text-2xl font-semibold">Ajustes de cotizaciones</h1><p className="text-sm text-[var(--muted-foreground)]">Los cambios aplican a nuevos cálculos. Los snapshots históricos no se modifican.</p></div>{error&&<p className="rounded border border-red-700 bg-red-950/40 p-3 text-red-200">{error}</p>}{msg&&<p className="rounded border border-emerald-700 bg-emerald-950/40 p-3 text-emerald-200">{msg}</p>}
 <div className="flex gap-2"><button className={cls} onClick={()=>setTab("parametros")}>Parámetros económicos</button><button className={cls} onClick={()=>setTab("perfiles")}>Perfiles de unidad</button></div>
 {tab==="parametros"?<section className="space-y-3"><div className="flex justify-between"><h2 className="font-semibold">Vigencias</h2>{puedeCrear&&<button className="btn-primary" onClick={nuevaVigencia}>Nueva vigencia</button>}</div><div className="overflow-auto"><table className="w-full text-sm"><thead><tr><th>Vigente desde</th><th>Combustible</th><th>IVA</th><th>Piloto/día</th><th>Auxiliar/día</th><th>Viático piloto</th><th>Viático auxiliar</th><th>Viático guía</th><th>Hotel</th><th>Margen</th></tr></thead><tbody>{datos?.parametros.map(p=><tr key={p.id}><td>{p.vigenteDesde} {p.esVigenciaActual&&<span className="rounded bg-emerald-800 px-1">Vigencia actual</span>}</td><td>{money(p.precioCombustibleGalon)}</td><td>{(p.ivaTasa*100).toLocaleString("es-GT")}%</td><td>{money(p.costoPilotoDia)}</td><td>{money(p.costoAuxiliarDia)}</td><td>{money(p.viaticoPilotoDia)}</td><td>{money(p.viaticoAuxiliarDia)}</td><td>{money(p.viaticoGuiaDia)}</td><td>{money(p.hotelDia)}</td><td>{p.margenObjetivo==null?"—":`${(p.margenObjetivo*100).toLocaleString("es-GT")}%`}</td></tr>)}</tbody></table></div>
 {mostrarParametro&&<form onSubmit={guardarParametro} className="grid gap-3 rounded border border-[var(--border)] p-4 md:grid-cols-3"><h3 className="md:col-span-3 font-semibold">Nueva vigencia (se insertará como historial nuevo)</h3>{[["vigenteDesde","Vigente desde","date"],["precioCombustibleGalon","Combustible/galón","number"],["ivaTasa","IVA (%)","number"],["costoPilotoDia","Piloto/día","number"],["costoAuxiliarDia","Auxiliar/día","number"],["viaticoPilotoDia","Viático piloto/día","number"],["viaticoAuxiliarDia","Viático auxiliar/día","number"],["viaticoGuiaDia","Viático guía/día","number"],["hotelDia","Hotel/día (opcional)","number"],["margenObjetivo","Margen objetivo (%)","number"]].map(([k,l,t])=><label key={k} className="text-sm">{l}<input required={!['hotelDia','margenObjetivo'].includes(k)} type={t} step={t==="number"?"0.01":undefined} className={`${cls} block w-full`} value={pa[k]??""} onChange={e=>setPa(x=>({...x,[k]:e.target.value}))}/></label>)}<div className="md:col-span-3 flex gap-2"><button className="btn-primary">Guardar vigencia</button><button type="button" className={cls} onClick={()=>setMostrarParametro(false)}>Cancelar</button></div></form>}</section>
 :<section className="space-y-3"><div className="flex justify-between"><h2 className="font-semibold">Perfiles de unidad</h2>{puedeCrear&&<button className="btn-primary" onClick={()=>editarPerfil()}>+ Nuevo perfil</button>}</div><div className="overflow-auto"><table className="w-full text-sm"><thead><tr><th>Código</th><th>Nombre</th><th>Estado</th><th>Rendimiento</th><th>GPS</th><th>Seguro</th><th>Aceite</th><th>Llantas</th><th>Depreciación</th><th>Refrigeración</th><th></th></tr></thead><tbody>{datos?.perfiles.map(p=><tr key={p.id}><td>{p.codigo}</td><td>{p.nombre}</td><td>{p.activo?"Activo":"Inactivo"}</td><td>{p.rendimientoKmGalon.toLocaleString("es-GT")} km/gal</td><td>{money(p.gpsMensual)}</td><td>{money(p.seguroVehiculoMensual)}</td><td>{money(p.costoAceiteServicio)}</td><td>{money(p.costoJuegoLlantas)}</td><td>{p.deprecValorBase==null?"No":money(p.deprecValorBase)}</td><td>{p.refrigValorBase==null?"No":money(p.refrigValorBase)}</td><td>{puedeEditar&&<button className={cls} onClick={()=>editarPerfil(p)}>Editar</button>}</td></tr>)}</tbody></table></div>
 {(perfilId!==null||pf!==vacioPerfil)&&<form onSubmit={guardarPerfil} className="grid gap-3 rounded border border-[var(--border)] p-4 md:grid-cols-3"><h3 className="md:col-span-3 font-semibold">{perfilId?"Editar perfil":"Nuevo perfil"}</h3>{Object.keys(vacioPerfil).filter(k=>k!=="activo").map(k=><label key={k} className="text-sm">{k.replace(/([A-Z])/g," $1")}{k==="codigo"?<input className={`${cls} block w-full uppercase`} disabled={perfilId!==null} value={pf[k as keyof PerfilForm] as string} onChange={e=>setPf(x=>({...x,codigo:e.target.value.toUpperCase()}))}/>:<input className={`${cls} block w-full`} type={k==="nombre"?"text":"number"} step="0.001" value={pf[k as keyof PerfilForm] as string} onChange={e=>setPf(x=>({...x,[k]:e.target.value}))}/>}</label>)}<label className="flex items-center gap-2"><input type="checkbox" checked={pf.activo} onChange={e=>setPf(x=>({...x,activo:e.target.checked}))}/> Activo</label><div className="md:col-span-3 flex gap-2"><button className="btn-primary">Guardar perfil</button><button type="button" className={cls} onClick={()=>{setPerfilId(null);setPf(vacioPerfil);}}>Cancelar</button></div></form>}</section>}</main>;
}
