"use client";
/* eslint-disable @typescript-eslint/no-explicit-any -- respuestas JSON heterogéneas del catálogo y detalle */
import { useEffect, useState } from "react";
import { CatalogoSearchSelect } from "./catalogo-search-select";
import { DOCUMENTO_EMISOR_DEFAULT, DOCUMENTOS_EMISOR, MARCAS_DOCUMENTO } from "@/lib/tms/cotizacion-documento";

const cls="rounded border border-[var(--border)] bg-[var(--input)] p-2";
type Catalogos={personal:any[];vehiculos:any[];clientes:any[];usuarios:any[]};
const hoy=()=>new Date().toISOString().slice(0,10);
const nueva=(fechaSolicitud=hoy())=>({fechaSolicitud,fechaViaje:fechaSolicitud,personalId:"",vehiculoId:"",clienteId:"",cantidad:"1",destino:"",montoUnitario:"0.00",motivoCambio:"",observaciones:""});
export default function ViaticosRequerimientosClient({slug}:{slug:string}){const [filas,setFilas]=useState<any[]>([]),[cat,setCat]=useState<Catalogos|null>(null),[form,setForm]=useState<any>({fechaRequerimiento:hoy(),empresaRequirente:DOCUMENTO_EMISOR_DEFAULT,requirenteUsuarioId:"",observaciones:"",lineas:[nueva()]}),[mostrar,setMostrar]=useState(false),[detalle,setDetalle]=useState<any>(null),[error,setError]=useState(""),[refresh,setRefresh]=useState(0);
  useEffect(()=>{const c=new AbortController();fetch(`/api/empresas/${slug}/tms/viaticos/requerimientos`,{cache:"no-store",signal:c.signal}).then(r=>r.json()).then(d=>setFilas(d.requerimientos||[])).catch(()=>{});return()=>c.abort();},[slug,refresh]);
  useEffect(()=>{if(!mostrar||cat)return;fetch(`/api/empresas/${slug}/tms/viaticos/requerimientos/catalogos`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setCat(d);}).catch(e=>setError(e.message));},[mostrar,cat,slug]);
  const linea=(i:number,p:any)=>setForm({...form,lineas:form.lineas.map((l:any,j:number)=>j===i?{...l,...p}:l)});
  async function guardar(){setError("");const res=await fetch(`/api/empresas/${slug}/tms/viaticos/requerimientos`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,requirenteUsuarioId:Number(form.requirenteUsuarioId),lineas:form.lineas.map((l:any)=>({...l,personalId:Number(l.personalId),vehiculoId:l.vehiculoId?Number(l.vehiculoId):null,clienteId:l.clienteId?Number(l.clienteId):null}))})});const d=await res.json();if(!res.ok){setError(d.error);return;}setMostrar(false);setForm({fechaRequerimiento:hoy(),empresaRequirente:DOCUMENTO_EMISOR_DEFAULT,requirenteUsuarioId:"",observaciones:"",lineas:[nueva()]});setRefresh(v=>v+1);}
  async function cargar(id:number){const r=await fetch(`/api/empresas/${slug}/tms/viaticos/requerimientos/${id}`,{cache:"no-store"});const d=await r.json();setDetalle(d.requerimiento);}
  async function accion(a:string){if(!detalle)return;const body:any={accion:a,version:Number(detalle.version)};if(a==="rechazar")body.motivo=prompt("Motivo del rechazo")||"";if(a==="entregar"){body.metodo=prompt("Método: EFECTIVO, TRANSFERENCIA o CHEQUE","EFECTIVO");body.referencia=prompt("Referencia")||null;body.observaciones=null;}if(a==="liquidar")body.observaciones=prompt("Observaciones de liquidación")||null;const r=await fetch(`/api/empresas/${slug}/tms/viaticos/requerimientos/${detalle.id}/estado`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setError(d.error);return;}setDetalle(d.requerimiento);setRefresh(v=>v+1);}
  return <section className="space-y-4"><div className="flex justify-between"><div><h2 className="text-lg font-semibold">Requerimientos manuales</h2><p className="text-sm text-[var(--muted)]">Captura transitoria independiente de Programación.</p></div><button className={cls} onClick={()=>setMostrar(!mostrar)}>+ Nuevo requerimiento</button></div>{error&&<p role="alert" className="text-red-400">{error}</p>}
  {mostrar&&<div className="space-y-3 rounded-xl border border-[var(--border)] p-4"><div className="grid gap-3 md:grid-cols-3"><label>Fecha del requerimiento<input className={`${cls} block w-full`} type="date" value={form.fechaRequerimiento} onChange={e=>setForm({...form,fechaRequerimiento:e.target.value})}/></label><label>Empresa requirente<select className={`${cls} block w-full`} value={form.empresaRequirente} onChange={e=>setForm({...form,empresaRequirente:e.target.value})}>{DOCUMENTOS_EMISOR.map(clave=><option key={clave} value={clave}>{MARCAS_DOCUMENTO[clave].etiqueta}</option>)}</select></label><label>Persona que requiere<select className={`${cls} block w-full`} value={form.requirenteUsuarioId} onChange={e=>setForm({...form,requirenteUsuarioId:e.target.value})}><option value="">Seleccionar</option>{cat?.usuarios.map(u=><option key={u.id} value={u.id}>{u.nombre}</option>)}</select></label></div>
  {form.lineas.map((l:any,i:number)=><div key={i} className="grid gap-2 rounded border border-[var(--border)] p-3 md:grid-cols-4"><CatalogoSearchSelect label="Colaborador" placeholder="Buscar nombre, código o DPI..." value={l.personalId} inputClassName={cls} options={(cat?.personal||[]).map(p=>({value:String(p.id),label:p.nombre,detail:`${p.codigo||""} · ${p.cargo}`,searchText:`${p.codigo||""} ${p.dpi||""}`}))} onChange={v=>{const p=cat?.personal.find(x=>String(x.id)===v);linea(i,{personalId:v,montoUnitario:p?Number(p.monto_sugerido).toFixed(2):"0.00"});}}/><CatalogoSearchSelect label="Unidad" placeholder="Buscar placa o unidad..." value={l.vehiculoId} inputClassName={cls} options={(cat?.vehiculos||[]).map(v=>({value:String(v.id),label:v.placa,searchText:`${v.descripcion||""} ${v.marca||""} ${v.modelo||""}`}))} onChange={v=>linea(i,{vehiculoId:v})}/><CatalogoSearchSelect label="Cliente" placeholder="Buscar cliente..." value={l.clienteId} inputClassName={cls} options={(cat?.clientes||[]).map(c=>({value:String(c.id),label:c.nombre}))} onChange={v=>linea(i,{clienteId:v})}/><label>Fecha solicitud<input className={`${cls} block w-full`} type="date" value={l.fechaSolicitud} onChange={e=>linea(i,{fechaSolicitud:e.target.value})}/></label><label>Fecha viaje<input className={`${cls} block w-full`} type="date" value={l.fechaViaje} onChange={e=>linea(i,{fechaViaje:e.target.value})}/></label><label>Destino<input className={`${cls} block w-full`} value={l.destino} onChange={e=>linea(i,{destino:e.target.value})}/></label><label>Cantidad<input className={`${cls} block w-full`} type="number" min="0.01" step="0.01" value={l.cantidad} onChange={e=>linea(i,{cantidad:e.target.value})}/></label><label>Monto unitario<input className={`${cls} block w-full`} type="number" min="0" step="0.01" value={l.montoUnitario} onChange={e=>linea(i,{montoUnitario:e.target.value})}/></label><label>Motivo del cambio<input className={`${cls} block w-full`} value={l.motivoCambio} onChange={e=>linea(i,{motivoCambio:e.target.value})}/></label><p className="self-end font-semibold">Total: Q {(Number(l.cantidad)*Number(l.montoUnitario)).toFixed(2)}</p>{form.lineas.length>1&&<button className="text-red-400" onClick={()=>setForm({...form,lineas:form.lineas.filter((_:any,j:number)=>j!==i)})}>Quitar línea</button>}</div>)}
  <div className="flex gap-2"><button className={cls} onClick={()=>setForm({...form,lineas:[...form.lineas,nueva(form.fechaRequerimiento)]})}>Agregar línea</button><button className="rounded bg-[var(--accent)] px-4 py-2 text-white" onClick={()=>void guardar()}>Guardar borrador</button></div></div>}
  <div className="space-y-2">{filas.map(f=><article key={f.id} className="rounded border border-[var(--border)] p-3"><div className="flex flex-wrap justify-between gap-2"><button className="text-left" onClick={()=>void cargar(f.id)}><b>{f.codigo}</b> · {f.fecha_requerimiento} · {f.requirente_nombre_snapshot} · {f.estado} · Q {Number(f.total).toFixed(2)}</button><span className="flex gap-2"><a className={cls} href={`/api/empresas/${slug}/tms/viaticos/requerimientos/${f.id}/exportar?formato=pdf`}>PDF</a><a className={cls} href={`/api/empresas/${slug}/tms/viaticos/requerimientos/${f.id}/exportar?formato=xlsx`}>Excel</a></span></div>{detalle?.id===f.id&&<div className="mt-3 overflow-auto"><table className="w-full text-xs"><thead><tr>{["Fecha solicitud","Fecha viaje","Colaborador","Cargo","Unidad","Cliente","Cantidad","Destino","Monto","Total"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{detalle.lineas.map((l:any)=><tr key={l.id}>{[l.fecha_solicitud,l.fecha_viaje,l.personal_nombre_snapshot,l.cargo_snapshot,l.placa_snapshot||"—",l.cliente_nombre_snapshot||"—",l.cantidad,l.destino,`Q ${l.monto_unitario}`,`Q ${l.total}`].map((x:any,j:number)=><td key={j} className="p-1">{x}</td>)}</tr>)}</tbody></table><div className="mt-2 flex gap-2">{detalle.estado==="BORRADOR"&&<button className={cls} onClick={()=>void accion("enviar")}>Enviar para autorización</button>}{detalle.estado==="PENDIENTE"&&<><button className={cls} onClick={()=>void accion("autorizar")}>Autorizar</button><button className={cls} onClick={()=>void accion("rechazar")}>Rechazar</button></>}{detalle.estado==="AUTORIZADO"&&<button className={cls} onClick={()=>void accion("entregar")}>Registrar entrega</button>}{detalle.estado==="ENTREGADO"&&<button className={cls} onClick={()=>void accion("liquidar")}>Liquidar</button>}</div></div>}</article>)}</div></section>;
}
