export const MODULOS_LIMPIEZA = [
  "rrhh",
  "rrhh_planillas",
  "rrhh_vacaciones",
  "rrhh_marcajes",
  "rrhh_incidencias",
  "rrhh_descuentos",
  "rrhh_horas_extra",
  "rrhh_inventario",
  "flota_kilometraje",
  "flota",
  "operaciones",
  "operaciones_viaticos",
  "operaciones_eliminar_rutas",
  "operaciones_multas",
  "pruebas_operaciones",
  "pruebas_viaticos",
  "pruebas_multas",
  "operaciones_accesos",
  "facturacion_clientes",
  "clientes",
  "contabilidad",
  "cms",
  "reciclaje",
  "tarimas",
] as const;

export type ModuloLimpieza = (typeof MODULOS_LIMPIEZA)[number];

export const MODULO_LIMPIEZA_LABEL: Record<ModuloLimpieza, string> = {
  rrhh: "RRHH completo (incluye empleados y todos sus datos)",
  rrhh_planillas: "RRHH · Planillas / nómina",
  rrhh_vacaciones: "RRHH · Vacaciones y solicitudes",
  rrhh_marcajes: "RRHH · Marcajes y jornadas",
  rrhh_incidencias: "RRHH · Incidencias y evidencias",
  rrhh_descuentos: "RRHH · Descuentos y cuotas",
  rrhh_horas_extra: "RRHH · Horas extra y prestaciones",
  rrhh_inventario: "RRHH · Inventario y entregas",
  flota_kilometraje: "Flota · Limpiar kilometraje actual de todos los vehículos",
  flota: "Flota / Predios (vehículos, viajes, lecturas…)",
  operaciones: "Operaciones · Programación y TMS juntos",
  operaciones_viaticos: "Operaciones · Viáticos sin autorizar",
  operaciones_eliminar_rutas: "Operaciones · Eliminar rutas",
  operaciones_multas: "Operaciones · Anular multas sin movimientos",
  pruebas_operaciones: "PRUEBAS · Borrar Programación/TMS, incluso viajes abiertos",
  pruebas_viaticos: "PRUEBAS · Borrar viáticos, incluso autorizados/pagados",
  pruebas_multas: "PRUEBAS · Multas + descuentos vinculados",
  operaciones_accesos: "Operaciones · Desactivar accesos de proveedores",
  facturacion_clientes: "Facturación clientes · Limpiar cuestionarios",
  clientes: "Clientes · Desactivar catálogo de la empresa",
  contabilidad: "Contabilidad",
  cms: "Sitio Web (CMS)",
  reciclaje: "Reciclaje",
  tarimas: "Tarimas",
};

/** Qué NO se borra al limpiar cada módulo (para la UI). */
export const MODULO_LIMPIEZA_NOTA: Record<ModuloLimpieza, string> = {
  rrhh: "Borra todos los datos operativos de RRHH, incluidos empleados. No toca usuarios ni configuración.",
  rrhh_planillas: "Borra periodos y líneas de nómina. Conserva empleados, descuentos y horas extra; los deja disponibles para probar otra planilla.",
  rrhh_vacaciones: "Borra solicitudes, registros, consumos y saldos de vacaciones. Conserva empleados y las incidencias que no sean de vacaciones.",
  rrhh_marcajes: "Borra jornadas y marcajes en ruta. Conserva empleados, vacaciones e incidencias.",
  rrhh_incidencias: "Borra incidencias y sus evidencias/consumos. Conserva empleados, marcajes y saldos de vacaciones.",
  rrhh_descuentos: "Borra descuentos nuevos y heredados, cuotas y abonos. Conserva empleados, planillas e inventario; las entregas quedan sin descuento vinculado.",
  rrhh_horas_extra: "Borra registros de horas extra y prestaciones adicionales. Conserva empleados y planillas.",
  rrhh_inventario: "Borra entregas, movimientos y artículos del inventario RRHH. Conserva empleados y descuentos; se desvincula el origen de inventario.",
  flota_kilometraje: "Limpia únicamente el kilometraje actual de los vehículos propios de esta empresa. Conserva vehículos, viajes, lecturas y servicios históricos.",
  flota: "No toca RRHH, planes TMS, usuarios ni contabilidad.",
  operaciones: "Borra juntos planes, viajes asociados ya cerrados, paradas, registros de evidencia, lecturas vinculadas al viaje y viáticos sin autorizar. Bloquea viajes abiertos y viáticos autorizados/pagados u otros vínculos externos. Conserva vehículos, kilometraje actual, lecturas independientes, empleados, clientes, rutas y configuración. No elimina archivos físicos.",
  operaciones_viaticos: "Borra solo viáticos PROGRAMADO sin autorización ni pago. Si existe alguno con movimientos, se bloquea toda la limpieza. Conserva viajes y configuración.",
  operaciones_eliminar_rutas: "Elimina definitivamente todas las rutas activas e inactivas y sus paradas maestras de la empresa seleccionada. Conserva clientes, ubicaciones y viajes con sus datos históricos. Requiere respaldo; si hay otros vínculos, se bloquea toda la limpieza.",
  operaciones_multas: "Anula las multas sin pagos, descuentos ni cierre usando las reglas existentes. Si alguna no admite anulación, no se modifica ninguna. Conserva revisiones mensuales, documentos e historial.",
  pruebas_operaciones: "IRREVERSIBLE: solo datos de prueba. Borra planes, viajes asociados incluso abiertos, paradas, registros de evidencia, lecturas del viaje y viáticos incluso autorizados, entregados o liquidados. Conserva vehículos y kilometraje actual, rutas, clientes, empleados, auditoría y archivos físicos. Bloquea referencias externas. Haz un respaldo antes y no registres nuevos movimientos durante la limpieza.",
  pruebas_viaticos: "IRREVERSIBLE: solo datos de prueba. Borra todos los viáticos de esta empresa, incluso autorizados, entregados o liquidados. No revierte transferencias bancarias reales. Conserva viajes y auditoría. Bloquea referencias externas. Haz un respaldo antes.",
  pruebas_multas: "IRREVERSIBLE: solo datos de prueba. Borra multas de esta empresa incluso pagadas/resueltas, revisiones mensuales, registros de documentos y sus descuentos/cuotas/abonos vinculados en RRHH. Conserva descuentos ajenos a multas, vehículos, empleados, auditoría y archivos físicos. Si hay cuotas vinculadas a planillas, limpia primero Planillas/nómina. No revierte pagos reales. Haz un respaldo antes.",
  operaciones_accesos: "Desactiva los accesos de proveedores de la empresa. Conserva usuarios y credenciales cifradas; se pueden reactivar.",
  facturacion_clientes: "Borra únicamente cuestionarios de clientes de esta empresa. Conserva clientes, perfil fiscal de la empresa, facturas y contabilidad.",
  clientes: "Desactiva clientes de esta empresa y su catálogo TMS. Conserva datos fiscales, rutas, viajes e historial; no elimina clientes de otras empresas.",
  contabilidad: "No toca RRHH, Flota ni TMS.",
  cms: "Solo secciones del sitio web de esa empresa.",
  reciclaje: "Solo lotes de reciclaje de esa empresa.",
  tarimas: "Solo órdenes de tarimas de esa empresa.",
};
