-- Requerimientos manuales de viáticos. MariaDB/InnoDB/utf8mb4.
-- Aditiva: no altera tms_viaticos ni su plan_id obligatorio.
CREATE TABLE IF NOT EXISTS tms_viatico_requerimientos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  empresa_id INT NOT NULL,
  codigo VARCHAR(40) NOT NULL,
  fecha_requerimiento DATE NOT NULL,
  empresa_requirente_nombre VARCHAR(200) NOT NULL,
  requirente_usuario_id INT NOT NULL,
  requirente_nombre_snapshot VARCHAR(200) NOT NULL,
  solicitante_usuario_id INT NOT NULL,
  solicitante_nombre_snapshot VARCHAR(200) NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
  total DECIMAL(14,2) NOT NULL DEFAULT 0,
  observaciones TEXT NULL,
  autorizado_por_usuario_id INT NULL,
  autorizado_por_nombre VARCHAR(200) NULL,
  autorizado_en DATETIME NULL,
  rechazado_por_usuario_id INT NULL,
  rechazado_por_nombre VARCHAR(200) NULL,
  rechazado_en DATETIME NULL,
  motivo_rechazo VARCHAR(1000) NULL,
  metodo_entrega VARCHAR(20) NULL,
  referencia_entrega VARCHAR(100) NULL,
  entregado_por_usuario_id INT NULL,
  entregado_por_nombre VARCHAR(200) NULL,
  entregado_en DATETIME NULL,
  observaciones_entrega VARCHAR(1000) NULL,
  liquidado_por_usuario_id INT NULL,
  liquidado_por_nombre VARCHAR(200) NULL,
  liquidado_en DATETIME NULL,
  observaciones_liquidacion VARCHAR(1000) NULL,
  version INT NOT NULL DEFAULT 1,
  creado_por INT NOT NULL,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_vreq_empresa_codigo (empresa_id, codigo),
  UNIQUE KEY uq_vreq_empresa_id (empresa_id, id),
  KEY idx_vreq_estado_fecha (empresa_id, estado, fecha_requerimiento),
  CONSTRAINT fk_vreq_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE,
  CONSTRAINT chk_vreq_estado CHECK (estado IN ('BORRADOR','PENDIENTE','AUTORIZADO','RECHAZADO','ENTREGADO','LIQUIDADO')),
  CONSTRAINT chk_vreq_metodo CHECK (metodo_entrega IS NULL OR metodo_entrega IN ('EFECTIVO','TRANSFERENCIA','CHEQUE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tms_viatico_requerimiento_lineas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  empresa_id INT NOT NULL,
  requerimiento_id INT NOT NULL,
  orden INT NOT NULL,
  fecha_solicitud DATE NOT NULL,
  fecha_viaje DATE NOT NULL,
  personal_id INT NOT NULL,
  empleado_id INT NULL,
  personal_nombre_snapshot VARCHAR(200) NOT NULL,
  cargo_snapshot VARCHAR(120) NOT NULL,
  vehiculo_id INT NULL,
  placa_snapshot VARCHAR(40) NULL,
  cliente_id INT NULL,
  cliente_nombre_snapshot VARCHAR(200) NULL,
  cantidad DECIMAL(10,2) NOT NULL DEFAULT 1,
  destino VARCHAR(300) NOT NULL,
  monto_sugerido DECIMAL(12,2) NOT NULL DEFAULT 0,
  monto_unitario DECIMAL(12,2) NOT NULL,
  motivo_cambio VARCHAR(300) NULL,
  total DECIMAL(14,2) NOT NULL,
  plan_id INT NULL,
  origen VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
  observaciones TEXT NULL,
  UNIQUE KEY uq_vreql_empresa_id (empresa_id, id),
  UNIQUE KEY uq_vreql_orden (empresa_id, requerimiento_id, orden),
  KEY idx_vreql_personal (empresa_id, personal_id),
  KEY idx_vreql_plan (empresa_id, plan_id),
  CONSTRAINT fk_vreql_req FOREIGN KEY (empresa_id, requerimiento_id) REFERENCES tms_viatico_requerimientos(empresa_id, id) ON DELETE CASCADE,
  CONSTRAINT fk_vreql_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE,
  -- FKs simples deliberadas: ON DELETE SET NULL sobre una FK compuesta
  -- (empresa_id, id_nullable) intentaría poner empresa_id=NULL, incompatible
  -- con el tenant NOT NULL. La aplicación valida empresa_id antes de escribir.
  -- tms_personal tampoco tiene índice UNIQUE (empresa_id,id) canónico.
  CONSTRAINT fk_vreql_personal FOREIGN KEY (personal_id) REFERENCES tms_personal(id),
  CONSTRAINT fk_vreql_vehiculo FOREIGN KEY (vehiculo_id) REFERENCES flota_vehiculos(id) ON DELETE SET NULL,
  CONSTRAINT fk_vreql_cliente FOREIGN KEY (cliente_id) REFERENCES tms_clientes(id) ON DELETE SET NULL,
  CONSTRAINT fk_vreql_plan FOREIGN KEY (plan_id) REFERENCES tms_planes_viaje(id) ON DELETE SET NULL,
  CONSTRAINT chk_vreql_origen CHECK (origen IN ('MANUAL','PROGRAMACION')),
  CONSTRAINT chk_vreql_cantidad CHECK (cantidad > 0),
  CONSTRAINT chk_vreql_montos CHECK (monto_unitario >= 0 AND total >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
