-- Propuesta: NO ejecutada por este PR. Ejecutar primero preflight-2026-09-compras-base.sql.
-- Aplicar SOLO si no hay DETENER. IF NOT EXISTS no corrige un esquema divergente.
-- MariaDB/InnoDB; sin ALTER, DROP, seeds o backfill. FKs externas requieren
-- tipos INT SIGNED e índices físicos verificados por preflight, no por schema.sql.
-- Las líneas conservan su id: la futura edición no debe borrarlas y recrearlas.
-- NIT no es UNIQUE: se permiten sucursales del mismo proveedor en un tenant.
CREATE TABLE IF NOT EXISTS compras_proveedores (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  empresa_id INT NOT NULL,
  nombre_comercial VARCHAR(200) NOT NULL,
  razon_social VARCHAR(250) NULL,
  nit VARCHAR(30) NULL,
  direccion VARCHAR(500) NULL,
  telefono VARCHAR(50) NULL,
  correo VARCHAR(200) NULL,
  contacto_nombre VARCHAR(200) NULL,
  contacto_telefono VARCHAR(50) NULL,
  contacto_correo VARCHAR(200) NULL,
  metodo_pago_habitual VARCHAR(80) NULL,
  banco VARCHAR(150) NULL,
  numero_cuenta VARCHAR(100) NULL,
  tipo_cuenta VARCHAR(80) NULL,
  titular_cuenta VARCHAR(200) NULL,
  dias_credito INT NULL,
  observaciones TEXT NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  creado_por INT NULL,
  actualizado_por INT NULL,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_compras_proveedor_empresa (empresa_id, id),
  INDEX idx_compras_proveedor_nombre (empresa_id, activo, nombre_comercial),
  INDEX idx_compras_proveedor_nit (empresa_id, nit),
  CONSTRAINT fk_cb_proveedores_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cb_proveedores_creador FOREIGN KEY (creado_por) REFERENCES usuarios(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cb_proveedores_editor FOREIGN KEY (actualizado_por) REFERENCES usuarios(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS compras_requerimientos (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  empresa_id INT NOT NULL,
  codigo VARCHAR(40) NOT NULL,
  fecha_requerimiento DATE NOT NULL,
  entidad_requirente_id INT NULL,
  entidad_requirente_nombre VARCHAR(200) NULL,
  requirente_usuario_id INT NULL,
  requirente_nombre VARCHAR(200) NULL,
  solicitante_usuario_id INT NULL,
  solicitante_nombre VARCHAR(200) NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente',
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  observaciones TEXT NULL,
  autorizante_usuario_id INT NULL,
  autorizante_nombre VARCHAR(200) NULL,
  autorizado_en DATETIME NULL,
  rechazado_en DATETIME NULL,
  motivo_rechazo VARCHAR(1000) NULL,
  version INT NOT NULL DEFAULT 1,
  creado_por INT NULL,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_compras_req_empresa (empresa_id, id),
  UNIQUE KEY uq_compras_req_codigo (empresa_id, codigo),
  INDEX idx_compras_req_fecha (empresa_id, estado, fecha_requerimiento),
  CONSTRAINT chk_compras_estado CHECK (estado IN ('Pendiente', 'Autorizada', 'Rechazada')),
  CONSTRAINT fk_cb_requerimientos_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cb_requerimientos_entidad FOREIGN KEY (empresa_id, entidad_requirente_id) REFERENCES cont_entidades(empresa_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_cb_requerimientos_requirente FOREIGN KEY (requirente_usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cb_requerimientos_solicitante FOREIGN KEY (solicitante_usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cb_requerimientos_autorizante FOREIGN KEY (autorizante_usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cb_requerimientos_creador FOREIGN KEY (creado_por) REFERENCES usuarios(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS compras_requerimiento_lineas (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  empresa_id INT NOT NULL,
  requerimiento_id INT NOT NULL,
  orden INT NOT NULL,
  vehiculo_id INT NULL,
  unidad_descripcion VARCHAR(200) NULL,
  fecha DATE NOT NULL,
  serie_factura VARCHAR(100) NULL,
  numero_factura VARCHAR(100) NULL,
  proveedor_id INT NOT NULL,
  proveedor_nombre_snapshot VARCHAR(200) NOT NULL,
  proveedor_razon_social_snapshot VARCHAR(250) NULL,
  proveedor_nit_snapshot VARCHAR(30) NULL,
  repuesto_descripcion VARCHAR(1000) NOT NULL,
  metodo_pago VARCHAR(80) NULL,
  condicion_pago VARCHAR(30) NULL,
  banco_snapshot VARCHAR(150) NULL,
  numero_cuenta_snapshot VARCHAR(100) NULL,
  dias_credito_snapshot INT NULL,
  total DECIMAL(12,2) NOT NULL,
  observaciones TEXT NULL,
  UNIQUE KEY uq_compras_linea_identidad (empresa_id, requerimiento_id, id),
  INDEX idx_compras_linea_orden (empresa_id, requerimiento_id, orden, id),
  INDEX idx_compras_linea_proveedor (empresa_id, proveedor_id),
  CONSTRAINT fk_cb_requerimiento_lineas_requerimiento FOREIGN KEY (empresa_id, requerimiento_id) REFERENCES compras_requerimientos(empresa_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_cb_requerimiento_lineas_proveedor FOREIGN KEY (empresa_id, proveedor_id) REFERENCES compras_proveedores(empresa_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_cb_requerimiento_lineas_vehiculo FOREIGN KEY (empresa_id, vehiculo_id) REFERENCES flota_vehiculos(empresa_id, id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS compras_linea_documentos (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  empresa_id INT NOT NULL,
  requerimiento_id INT NOT NULL,
  linea_id INT NOT NULL,
  tipo VARCHAR(20) NOT NULL,
  ruta_relativa VARCHAR(1000) NOT NULL,
  nombre_original VARCHAR(500) NOT NULL,
  mime VARCHAR(100) NOT NULL,
  tamano BIGINT NOT NULL,
  sha256 CHAR(64) NULL,
  subido_por_usuario_id INT NOT NULL,
  subido_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  retirado TINYINT(1) NOT NULL DEFAULT 0,
  retirado_por_usuario_id INT NULL,
  retirado_en DATETIME NULL,
  motivo_retiro VARCHAR(1000) NULL,
  INDEX idx_compras_documento_linea (empresa_id, requerimiento_id, linea_id, retirado),
  CONSTRAINT chk_compras_documento_tipo CHECK (tipo IN ('FACTURA', 'COMPROBANTE')),
  CONSTRAINT fk_cb_linea_documentos_linea FOREIGN KEY (empresa_id, requerimiento_id, linea_id) REFERENCES compras_requerimiento_lineas(empresa_id, requerimiento_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_cb_linea_documentos_subido FOREIGN KEY (subido_por_usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cb_linea_documentos_retirado FOREIGN KEY (retirado_por_usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
